use std::fmt;

use serde_json::Value;

pub(crate) mod http;
pub(crate) mod stdio;

/// One transport-independent JSON-RPC request generated by the diagnostic
/// application. Values remain redacted from `Debug`; concrete transports add
/// their own framing and request metadata.
pub(crate) struct ProbeRequest {
    id: i64,
    expects_response: bool,
    bytes: Vec<u8>,
    method: String,
    principal_name: Option<String>,
    mirrored_fields: Vec<MirroredField>,
}

impl ProbeRequest {
    pub(crate) fn new(id: i64, bytes: Vec<u8>) -> Self {
        assert!(
            id >= 0,
            "a locally generated JSON-RPC request id must be non-negative"
        );
        let value: Value = serde_json::from_slice(&bytes)
            .expect("a locally generated request must contain valid JSON");
        let object = value
            .as_object()
            .expect("a locally generated request must be a JSON object");
        let method = object
            .get("method")
            .and_then(Value::as_str)
            .expect("a locally generated request must name its method")
            .to_owned();
        let params = object.get("params").and_then(Value::as_object);
        let principal_name = params
            .and_then(|params| params.get("name").or_else(|| params.get("uri")))
            .and_then(Value::as_str)
            .map(str::to_owned);

        Self {
            id,
            expects_response: true,
            bytes,
            method,
            principal_name,
            mirrored_fields: Vec::new(),
        }
    }

    pub(crate) fn notification(bytes: Vec<u8>) -> Self {
        let value: Value = serde_json::from_slice(&bytes)
            .expect("a locally generated notification must contain valid JSON");
        let object = value
            .as_object()
            .expect("a locally generated notification must be a JSON object");
        assert!(
            !object.contains_key("id"),
            "a locally generated notification must omit an id"
        );
        let method = object
            .get("method")
            .and_then(Value::as_str)
            .expect("a locally generated notification must name its method")
            .to_owned();
        Self {
            id: -1,
            expects_response: false,
            bytes,
            method,
            principal_name: None,
            mirrored_fields: Vec::new(),
        }
    }

    pub(crate) fn with_mirrored_fields(mut self, fields: Vec<MirroredField>) -> Self {
        self.mirrored_fields = fields;
        self
    }

    pub(crate) const fn id(&self) -> i64 {
        self.id
    }

    pub(crate) const fn expects_response(&self) -> bool {
        self.expects_response
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    pub(crate) fn method(&self) -> &str {
        &self.method
    }

    pub(crate) fn principal_name(&self) -> Option<&str> {
        self.principal_name.as_deref()
    }

    pub(crate) fn mirrored_fields(&self) -> &[MirroredField] {
        &self.mirrored_fields
    }
}

impl fmt::Debug for ProbeRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ProbeRequest")
            .field("id", &self.id)
            .field("expects_response", &self.expects_response)
            .field("value", &"[REDACTED]")
            .field("byte_count", &self.bytes.len())
            .field("mirrored_field_count", &self.mirrored_fields.len())
            .finish()
    }
}

/// A validated `x-mcp-header` mapping. Both strings may contain tool-derived
/// values, so its debug representation exposes only their byte counts.
#[derive(Clone, Eq, PartialEq)]
pub(crate) struct MirroredField {
    suffix: String,
    value: String,
}

impl MirroredField {
    pub(crate) fn new(suffix: String, value: String) -> Self {
        Self { suffix, value }
    }

    pub(crate) fn suffix(&self) -> &str {
        &self.suffix
    }

    pub(crate) fn value(&self) -> &str {
        &self.value
    }
}

impl fmt::Debug for MirroredField {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("MirroredField")
            .field("suffix", &"[REDACTED]")
            .field("suffix_bytes", &self.suffix.len())
            .field("value", &"[REDACTED]")
            .field("value_bytes", &self.value.len())
            .finish()
    }
}

pub(crate) trait Conversation {
    fn next_request(&mut self, previous: Option<&ProbeResponse>) -> Option<ProbeRequest>;
}

pub(crate) struct ProbeResponse {
    request_id: i64,
    bytes: Vec<u8>,
}

impl ProbeResponse {
    pub(crate) fn new(request_id: i64, bytes: Vec<u8>) -> Self {
        Self { request_id, bytes }
    }

    pub(crate) const fn request_id(&self) -> i64 {
        self.request_id
    }

    #[cfg(test)]
    pub(crate) fn byte_count(&self) -> usize {
        self.bytes.len()
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }
}

impl fmt::Debug for ProbeResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ProbeResponse")
            .field("request_id", &self.request_id)
            .field("value", &"[REDACTED]")
            .field("byte_count", &self.bytes.len())
            .finish()
    }
}
